import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

/**
 * Create a forensic report record
 */
export const create = mutation({
  args: {
    artworkId: v.id("artworks"),
    detectionLogId: v.optional(v.id("detectionLogs")),
    reportFileId: v.id("_storage"),
    reportFileName: v.string(),
    reportType: v.union(
      v.literal("ownership"),
      v.literal("detection"),
      v.literal("full")
    ),
    generatedBy: v.optional(v.id("users")),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("forensicReports", {
      ...args,
      generatedAt: Date.now(),
    });
  },
});

/**
 * Get reports for an artwork
 */
export const listByArtwork = query({
  args: { artworkId: v.id("artworks") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("forensicReports")
      .withIndex("by_artwork", (q) => q.eq("artworkId", args.artworkId))
      .order("desc")
      .collect();
  },
});

/**
 * Get report by ID
 */
export const get = query({
  args: { id: v.id("forensicReports") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

/**
 * Get reports generated by a user
 */
export const listByUser = query({
  args: {
    userId: v.id("users"),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const query = ctx.db
      .query("forensicReports")
      .withIndex("by_user", (q) => q.eq("generatedBy", args.userId))
      .order("desc");

    if (args.limit) {
      return await query.take(args.limit);
    }

    return await query.collect();
  },
});
